version: '2.1'
volumes:
  auth-data: {}
  calendar-data: {}
services:
  inkyshot:
    build:
      context: ./inkyshot
    privileged: true
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: '1'
    volumes:
      - 'calendar-data:/usr/app/calendar-data'
  calendar-server:
    build:
      context: ./calendar-server
    privileged: true
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: '1'
    ports:
      - "80:80"
    volumes:
      - 'auth-data:/usr/app/auth-data'
      - 'calendar-data:/usr/app/calendar-data'
  wifi-connect:
    build:
      context: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
